tildes y typos arreglados en el post
Roberto-B-23/Roberto-B.github.io pull request #1
Opened 2020-02-23 23:11 UTC by Roberto-B-23

no debimos pasar este error a master.

2020-02-24 18:06 UTC, ROBERTITO-06 requested changes
En vez de usar tildes directas usa entidades HTML

2020-02-24 20:11 UTC, ROBERTITO-06 requested changes
YES

2020-02-25 00:14 UTC, Roberto-B-23 commented
cambios hechos porfavor hasme el merge

2020-02-25 00:45 UTC, ROBERTITO-06 approved these changes
Exelente eso era!

2020-02-25 00:45 UTC, ROBERTITO-06 approved these changes
ecelente eso era

2020-02-25 00:50 UTC, merged